config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles
  resources :tags
  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :article_tagmentations
  has_many :tags, through: :article_tagmentations

  default_scope -> { order('created_at DESC') }

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  validates_presence_of :title, :slug

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]
  before_action :set_article_redirect, only: [:show]
  before_action :logged_in_user, except: [:show]
  #http_basic_authenticate_with name: ENV["BLOG_USERNAME"], password: ENV["BLOG_PASSWORD"],
  #                             except: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    unless @article.publish?
      flash[:warning] = "The requested resource is currently not available."
      redirect_to root_url
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        if @article.publish?
          format.html { redirect_to @article, notice: 'Article was successfully created.' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
          format.json { render :show, status: :created, location: articles_path }
        end
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        if @article.publish?
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { redirect_to articles_path, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: articles_path }
        end
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_redirect
      @article = Article.friendly.find(params[:id])
      # If an old id or a numeric id was used to find the record, then
      # the request path will not match the article_path, and we should do
      # a 301 redirect that uses the current friendly id.     
      if request.path != article_path(@article)
        redirect_to @article, status: :moved_permanently
      end
    end

    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:author, :title, :content, :publish, :slug, :tag_ids => [] )
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join("-") do
        Pygments.highlight(code, lexer: language, options: { lineanchors: "line" })
      end
    end
  end

  def markdown(text)
    options = { 
      filter_html:     true,
      no_images:       false,
      no_links:        false,
      no_styles:       false,
      escape_html:     false,
      safe_links_only: false,
      with_toc_data:   false,
      hard_wrap:       true,
      xhtml:           false,
      prettify:        false
    }
    extensions = {
      no_intra_emphasis:            true,
      tables:                       false,
      fenced_code_blocks:           true,
      autolink:                     true,
      disable_indented_code_blocks: false,
      strikethrough:                true,
      lax_spacing:                  true,  # This causes code blocks not to display??
      space_after_headers:          false,
      superscript:                  true,
      underline:                    false,
      highlight:                    false,
      quote:                        false,
      footnotes:                    false 
    }
    #renderer = Redcarpet::Render::HTML.new(options)
    renderer = HTMLwithPygments.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, wrapper: :inline_form do |f| %>

  <%= f.input :author, placeholder: "author" %>
  <%= f.input :title, placeholder: "title" %>
  <%= f.input :content, placeholder: "your content ..", input_html: { rows: "15" } %>
  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, item_wrapper_tag: :span, item_wrapper_class: "label label-info" %>
  <%= f.input :publish, wrapper: :vertical_boolean %>
  <%= f.button :submit, class: "btn btn-sm btn-info" %>

<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "edit") %>

<h1>edit article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<% provide(:title, "articles list") %>

<h1>listing articles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>author</th>
      <th>title</th>
      <th>tags</th>
      <th>created</th>
      <th>last updated</th>
      <th colspan="2">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.author %></td>
        <% if article.publish? %>
          <td><%= link_to article.title, article %></td>
        <% else %>
          <td><%= link_to article.title, "#", class: "disabled" %></td>
        <% end %>
        <td>
          <% article.tags.each do |tag| %>
            <%= link_to tag.name, tag %>
          <% end %>
        </td>
        <td><%= article.created_at %></td>
        <td><%= article.updated_at %></td>
        <td><%= link_to "edit", edit_article_path(article), class: "btn btn-info btn-xs" %></td>
        <td><%= link_to "destroy", article, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "new article", new_article_path, class: "btn btn-sm btn-info" %>

app/views/articles/new.html.erb
<% provide(:title, "new") %>

<h1>new article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<% @article.tags.each do |tag| %>
  <span class="label label-info"><%= tag.name %></span>
<% end %>
<h2><%= @article.title %></h2>
<h6>by <%= @article.author %></h6>
<h6>Last updated: <%= @article.updated_at %></h6>

<p><%= markdown(@article.content) %></p>