config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles
  resources :tags
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  #http_basic_authenticate_with name: ENV["BLOG_USERNAME"], password: ENV["BLOG_PASSWORD"]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'Thank you for signing up!.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
 
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user, wrapper: :inline_form do |f| %>

  <%= f.input :name, placeholder: "name" %>
  <%= f.input :email, placeholder: "email" %>
  <%= f.input :password, placeholder: "password" %>
  <%= f.input :password_confirmation, placeholder: "password confirmation" %>
  <%= f.button :submit, class: "btn btn-sm btn-info" %>

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "edit") %>

<h1>edit user</h1>

<%= render "form" %>

app/views/users/index.html.erb
<% provide(:title, "users list") %>

<h1>listing users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th>created</th>
      <th>last updated</th>
      <th colspan="2">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to "edit", edit_user_path(user), class: "btn btn-info btn-xs" %></td>
        <td><%= link_to "destroy", user, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "new user", new_user_path, class: "btn btn-sm btn-info" %>

app/views/users/new.html.erb
<% provide(:title, "new") %>

<h1>new user</h1>

<%= render "form" %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>