config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles
  resources :tags
  resources :users

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :article_tagmentations
  has_many :articles, through: :article_tagmentations

  validates :name, presence: true, uniqueness: { case_senstiive: false }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  #http_basic_authenticate_with name: ENV["BLOG_USERNAME"], password: ENV["BLOG_PASSWORD"]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_url, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for @tag, wrapper: :inline_form do |f| %>

  <%= f.input :name, placeholder: "tag name" %>
  <%= f.button :submit, class: "btn btn-sm btn-info" %>

<% end %>

app/views/tags/edit.html.erb
<% provide(:title, "edit") %>

<h1>edit tag</h1>

<%= render "form" %>

app/views/tags/index.html.erb
<% provide(:title, "tags list") %>

<h1>listing tags</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>tag</th>
      <th>articles tagged</th>
      <th colspan="2">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.name, tag %></td>
        <td>
          <ul class="list-unstyled">
            <% tag.articles.each do |article| %>
              <li><%= link_to article.title, article %></li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to "edit", edit_tag_path(tag), class: "btn btn-xs btn-info" %></td>
        <td><%= link_to "destroy", tag, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "new tag", new_tag_path, class: "btn btn-sm btn-info" %>

app/views/tags/new.html.erb
<% provide(:title, "new") %>

<h1>new tag</h1>

<%= render "form" %>

app/views/tags/show.html.erb
<% provide(:title, "show") %>

<div class="row">
  <aside class="col-md-4">
    <section class="tag_info">
      <h1>
        <%= @tag.name %>
      </h1>
    </section>
  </aside>
</div>