config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#index'

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :articles
  resources :tags
  resources :users

end

app/views/layouts/_head_meta.html.erb
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Blog">
  <meta name="author" content="Jens Jap">
  <link rel="icon" href="/favicon.ico">

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">

  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

app/views/layouts/_navbar_left.html.erb
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">home</a></li>
        <li><a href="<%= about_path %>">about</a></li>
        <li><a href="<%= contact_path %>">contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">portfolio <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">Code Repositories</li>
            <li><a href="https://github.com/jensjap" target="_blank">github</a></li>
            <li><a href="https://bitbucket.org/jensjap" target="_blank">bitbucket</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Current Projects</li>
            <li><a href="http://srdr.ahrq.gov" target="_blank">srdr</a></li>
            <li><a href="http://abstrackr.cebm.brown.edu" target="_blank">abstrackR</a></li>
            <li><a href="http://www.cebm.brown.edu" target="_blank">cebm brown</a></li>
          </ul>
        </li>
      </ul>
<!-- Save this for later.
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
-->

app/views/layouts/_navbar_right.html.erb
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "articles", articles_path %></li>
          <li><%= link_to "tags", tags_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">articles <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">index</li>
            <% Article.all.each do |article| %>
              <% if article.publish? %>
                <li><%= link_to article.title, article_path(article) %></li>
              <% else %>
                <li><%= link_to article.title, "#", class: "disabled" %></li>
              <% end %>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if logged_in? %>
              <li>
                <%= link_to "log out", logout_path, method: "delete" %>
              </li>
            <% else %>
              <li>
                <%= link_to "log in", login_path %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">infalliblekitty</a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
        <%= render "layouts/navbar_left" %>
        <%= render "layouts/navbar_right" %>
  
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= render "layouts/head_meta"%>

</head>
<body role="document">

  <%= render "layouts/navigation" %>
  
  <div class="container" role="main">
    <div class="row">
      <div class="col-md-12">
  
        <!-- Iterate through each flash message and display accordingly to type -->
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= bootify(name) %>" role="alert">
            <a class="close" data-dismiss="alert">x</a>
            <%= msg %>
          </div>
        <% end %>
  
        <!-- Page content -->
        <%= yield %>

        <hr>

        <%= debug(params) if Rails.env.development? %>
  
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container role="main" -->

</body>
</html>